L2M/Models/Genre.cs
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using System.Collections.Generic;
using Microsoft.AspNetCore.Http;

namespace L2M.Models
{
    [Table("genre")]
    public class Genre
    {
        [Key, Column("genre_id")]
        //[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int GenreId { get; set; }

        [Required, StringLength(50)]
        public string Name { get; set; }
        [Column("img_url")]
        public string? ImgUrl { get; set; }
        public string? Description { get; set; }

        public ICollection<Song>? Songs { get; set; }
    }
}

L2M/Areas/Admin/Controllers/GenresController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using L2M.Data;
using L2M.Models;
using L2M.Services;
using System.IO;
using Microsoft.AspNetCore.Hosting;

namespace L2M.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class GenresController : Controller
    {
        private readonly IWebHostEnvironment _webHostEnviroment;

        public GenresController(IWebHostEnvironment hostEnvironment)
        {
            this._webHostEnviroment = hostEnvironment;
            GenreService.getContext();
        }

        // GET: Genres1
        public IActionResult Index()
        {
            return View(GenreService.GetGenre());
        }
        // GET: Genres1/Details/5
        public IActionResult Detail(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var genre = GenreService.GetGenre((int)id);

            if (genre == null)
            {
                return NotFound();
            }

            return View(genre);
        }
         // GET: Genres1/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Genres1/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("Name,ImgUrl,Description")] Genre genre)
        {
            if (ModelState.IsValid)
            {
                var files = HttpContext.Request.Form.Files;
                if (files.Count == 0)
                {
                    genre.ImgUrl = "~/img/defaultImg.png";
                }
                else { 
                string wwwRootPath = _webHostEnviroment.WebRootPath;
                string path = wwwRootPath + "/img/genre/";
                string fileName = Path.GetFileNameWithoutExtension(files[0].FileName);
                string extension = Path.GetExtension(files[0].FileName);
                fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
                using (var fileStream = new FileStream(Path.Combine(path, fileName ), FileMode.Create))
                {
                    files[0].CopyTo(fileStream);
                }
                genre.ImgUrl = "~/img/genre/" + fileName;
                }
                int count = GenreService.PostGenre(genre);
                if (count > 0)
                {
                    TempData["Success"] = "Added";
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    TempData["Error"] = "Error add";
                    return View(genre);
                }
            }
            TempData["Error"] = "Validation";
            return View(genre);
        }

        // GET: Genres1/Edit/5
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var genre = GenreService.GetGenre((int)id);
            if (genre == null)
            {
                return NotFound();
            }
            return View(genre);
        }

        // POST: Genres1/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit([Bind("GenreId,Name,ImgUrl,Description")] Genre genre)
        {
            if (ModelState.IsValid)
            {
                var oldObj = GenreService.GetGenreToEdit(genre);
                if (oldObj.ImgUrl == "" || oldObj.ImgUrl == null)
                {
                    oldObj.ImgUrl = "~/img/defaultImg.png";
                }
                string oldFileName = Path.GetFileNameWithoutExtension(oldObj.ImgUrl);
                string oldFileNameExtension = Path.GetExtension(oldObj.ImgUrl);
                var files = HttpContext.Request.Form.Files;
                if (files.Count > 0)
                {
                    string wwwRootPath = _webHostEnviroment.WebRootPath;
                    string path = wwwRootPath + "/img/genre/";
                    string fileName = Path.GetFileNameWithoutExtension(files[0].FileName);
                    string extension = Path.GetExtension(files[0].FileName);
                    if (oldFileName != "defaultImg" || oldFileName != "")
                    {
                        oldFileName = oldFileName + oldFileNameExtension;
                        var oldFile = Path.Combine(path, oldFileName);
                        if (System.IO.File.Exists(oldFile))
                        {
                            System.IO.File.Delete(oldFile);
                        }
                    }
                    fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
                    using (var fileStream = new FileStream(Path.Combine(path, fileName), FileMode.Create))
                    {
                        files[0].CopyTo(fileStream);
                    }
                    genre.ImgUrl = "~/img/genre/" + fileName;
                }
                else if (files.Count == 0)
                {
                    genre.ImgUrl = oldObj.ImgUrl;
                }

                int count = GenreService.PutGenre(genre);
                if (count > 0)
                {
                    TempData["Success"] = "Edited";
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    TempData["Error"] = "Error edit";
                    return View(genre);
                }
            } else
            {
                TempData["Error"] = "Error edit";
            }
            return View(genre);
        }

        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        public IActionResult Delete(int id)
        {
            var obj = GenreService.GetGenre((int)id);
            if (obj == null)
            {
                TempData["Error"] = "Error";
                return RedirectToAction("Index");
            }
            string path = _webHostEnviroment.WebRootPath + "/img/genre/";
            string oldFileName = Path.GetFileNameWithoutExtension(obj.ImgUrl);
            string oldFileNameExtension = Path.GetExtension(obj.ImgUrl);
            if (oldFileName != "defaultImg" || oldFileName != "")
            {
                oldFileName = oldFileName + oldFileNameExtension;
                var oldFile = Path.Combine(path, oldFileName);
                if (System.IO.File.Exists(oldFile))
                {
                    System.IO.File.Delete(oldFile);
                }
            }
            int count = GenreService.DeleteGenre(id);
            if (count > 0)
            {
                TempData["Success"] = "Deleted";
                return RedirectToAction(nameof(Index));
            }
            TempData["Error"] = "Error delete";
            return RedirectToAction(nameof(Index));
        }

    }
}

L2M/Areas/Admin/Views/Genres/Create.cshtml
@model L2M.Models.Genre
@{
    ViewBag.Title = "Thêm thể loại";
}

<!-- Page Heading -->
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Thể loại</h1>
    <a asp-controller="Genres" asp-action="Index" asp-area="Admin" class="d-none d-sm-inline-block btn btn btn-primary shadow-sm">
        <i class="fas fa-long-arrow-alt-left text-white-50"></i><b> Quay trở lại</b>
    </a>
</div>

<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Thêm thể loại</h6>
    </div>
    <div class="card-body">
        <form asp-action="Create" class="formGenre" id="formGenre" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @*<input type="hidden" asp-for="GenreId" />*@
            <div class="row">
                <div class="form-group col-lg-3 col-sm-12">
                    <div class="upload_img">
                        <img src="~/admin/img/noimg.webp" class="img_name" id="imgPreview" />
                        <input type="file" asp-for="ImgUrl" accept="image/*" class="form-control" placeholder="Tải lên hình ảnh" id="photo">
                    </div>
                </div>
                <div class="col-lg-9 col-sm-12">
                    <div class="form-group">
                        <label asp-for="Name">Tên thể loại</label>
                        <input type="text" asp-for="Name" class="form-control" placeholder="Tên thể loại">
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Description">Mô tả</label>
                        <textarea id="edit-text" placeholder="Mô tả" class="form-control" asp-for="Description"></textarea>
                    </div>
                    <button type="submit" class="btn btn-primary float-right">Lưu</button>
                </div>
            </div>
        </form>
    </div>
</div>
@section Scripts{
    <script>
    $(document).ready(function () {
        if ('@TempData["Error"]' == "Error add") {
    swal("Có lỗi", "Đã có lỗi xảy ra, vui lòng thử lại!", "error");
    } else if ('@TempData["Error"]' == "Validation") {
    swal("Cảnh báo", "Không được bỏ trống, vui lòng thử lại!", "warning");
    }
    </script>
    <partial name="_ValidationScriptsPartial" />
}

L2M/Areas/Admin/Views/Genres/Detail.cshtml
@model L2M.Models.Genre
@{
    ViewBag.Title = "Thông tin thể loại";
}

<!-- Page Heading -->
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Thể loại</h1>
    <a asp-controller="Genres" asp-action="Index" asp-area="Admin" class="d-none d-sm-inline-block btn btn btn-primary shadow-sm">
        <i class="fas fa-long-arrow-alt-left text-white-50"></i><b> Quay trở lại</b>
    </a>
</div>

<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Thông tin thể loại</h6>
    </div>
    <div class="card-body">
        <form asp-action="Edit" class="formGenre" id="formGenre" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="GenreId" />
            <div class="row">
                <div class="form-group col-lg-3 col-sm-12">
                    <div class="upload_img">
                        @if (Model.ImgUrl == "")
                        {
                            @:<img src="~/admin/img/noimg.webp" class="img_name" id="imgPreview" />
                        }
                        else
                        {
                            @:<img src="@Url.Content(@Model.ImgUrl)" class="img_name" id="imgPreview" />
                        }
                        <input type="file" asp-for="ImgUrl" accept="image/*" class="form-control" placeholder="Tải lên hình ảnh" id="photo">
                    </div>
                </div>
                <div class="col-lg-9 col-sm-12">
                    <div class="form-group">
                        <label asp-for="Name">Tên thể loại</label>
                        <input type="text" asp-for="Name" class="form-control" placeholder="Tên thể loại">
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Description">Mô tả</label>
                        <textarea id="edit-text" placeholder="Mô tả" class="form-control" asp-for="Description"></textarea>
                    </div>
                    <button type="submit" class="btn btn-primary float-right">Cập nhật</button>
                </div>
            </div>
        </form>
    </div>
</div>
@section Scripts{
    <script>
        $(document).ready(function () {
            if ('@TempData["Error"]' == "Error edit") {
                swal("Có lỗi", "Đã có lỗi xảy ra, vui lòng thử lại!", "error");
            } else if ('@TempData["Error"]' == "Validation") {
                swal("Cảnh báo", "Không được bỏ trống, vui lòng thử lại!", "warning");
            }
        }
    </script>
    <partial name="_ValidationScriptsPartial" />
}

L2M/Areas/Admin/Views/Genres/Edit.cshtml
@model L2M.Models.Genre
@{
    ViewBag.Title = "Chỉnh sửa thể loại";
}

<!-- Page Heading -->
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Thể loại</h1>
    <a asp-controller="Genres" asp-action="Index" asp-area="Admin" class="d-none d-sm-inline-block btn btn btn-primary shadow-sm">
        <i class="fas fa-long-arrow-alt-left text-white-50"></i><b> Quay trở lại</b>
    </a>
</div>

<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Chỉnh sửa thể loại</h6>
    </div>
    <div class="card-body">
        <form asp-action="Edit" class="formGenre" id="formGenre" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="GenreId" />
            <div class="row">
                <div class="form-group col-lg-3 col-sm-12">
                    <div class="upload_img">
                        @if (Model.ImgUrl == "")
                        {
                            @:<img src="~/admin/img/noimg.webp" class="img_name" id="imgPreview" />
                        }
                        else
                        {
                            @:<img src="@Url.Content(@Model.ImgUrl)" class="img_name" id="imgPreview" />
                        }
                        <input type="file" asp-for="ImgUrl" accept="image/*" class="form-control" placeholder="Tải lên hình ảnh" id="photo">
                    </div>
                </div>
                <div class="col-lg-9 col-sm-12">
                    <div class="form-group">
                        <label asp-for="Name">Tên thể loại</label>
                        <input type="text" asp-for="Name" class="form-control" placeholder="Tên thể loại">
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Description">Mô tả</label>
                        <textarea id="edit-text" placeholder="Mô tả" class="form-control" asp-for="Description"></textarea>
                    </div>
                    <button type="submit" class="btn btn-primary float-right">Lưu</button>
                </div>
            </div>
        </form>
    </div>
</div>
@section Scripts{
    <script>
        $(document).ready(function () {
            if ('@TempData["Error"]' == "Error edit") {
                swal("Có lỗi", "Đã có lỗi xảy ra, vui lòng thử lại!", "error");
            } else if ('@TempData["Error"]' == "Validation") {
                swal("Cảnh báo", "Không được bỏ trống, vui lòng thử lại!", "warning");
            }
        }
    </script>
    <partial name="_ValidationScriptsPartial" />
}

L2M/Areas/Admin/Views/Genres/Index.cshtml
@model IEnumerable<L2M.Models.Genre>
@{
    ViewBag.Title = "Thể loại";
}

<!-- Page Heading -->
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Thể loại</h1>
    <a asp-controller="Genres" asp-action="Create" asp-area="Admin" class="d-none d-sm-inline-block btn btn btn-primary shadow-sm">
        <i class="fas fa-plus text-white-50"></i><b> Thêm thể loại</b>
    </a>
</div>

<!-- DataTales Example -->
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Danh sách thể loại</h6>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-hover" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>Ảnh bìa</th>
                        <th>Tên thể loại</th>
                        <th>Mô tả</th>
                        <th>Tác vụ</th>
                    </tr>
                </thead>
                <tfoot>
                    <tr>
                        <th>Ảnh bìa</th>
                        <th>Tên thể loại</th>
                        <th>Mô tả</th>
                        <th>Tác vụ</th>
                    </tr>
                </tfoot>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr asp-action="Detail" asp-route-id="@item.GenreId">
                            <td>
                                @if (item.ImgUrl == "")
                                {
                                    @:<img src="~/admin/img/defaultImg.png" width="100" />
                                }
                                else
                                {
                                    @:<img src="@Url.Content(item.ImgUrl)" width="100" />
                                }
                            </td>
                            <td>@item.Name</td>
                            <td>@item.Description</td>
                            <td>
                                <a class="text-primary mr-lg-2" asp-action="Edit" asp-route-id="@item.GenreId"><i class="fas fa-edit"></i></a>&nbsp;
                                <a class="text-danger" onclick="Delete(event, 'thể loại', '@item.Name', '/Admin/Genres/Delete?id=@item.GenreId')"><i class="fas fa-trash-alt"></i></a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>
@section Scripts{
    <script>
    $(document).ready(function () {
       if('@TempData["Success"]' == "Deleted"){
           swal("Đã xóa", "Xóa thành công!", "success");
       }
       else if ('@TempData["Error"]' == "Error Delete") {
           swal("Có lỗi", "Đã có lỗi xảy ra, vui lòng thử lại!", "error");
       } else if('@TempData["Success"]' == "Added"){
           swal("Đã thêm", "Thêm thành công!", "success");
           }
       else if('@TempData["Success"]' == "Edited"){
           swal("Đã sửa", "Chỉnh sửa thành công!", "success");
       }
    </script>
    <script type="text/javascript" src="~/admin/js/site.js"></script>
    <partial name="_ValidationScriptsPartial" />
}

L2M/Areas/Admin/Views/Genres/UpsertGenre.cshtml
@{
    ViewBag.Title = "Thêm thể loại";
}

<!-- Page Heading -->
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Thể loại</h1>
    <a asp-controller="Genres" asp-action="Index" asp-area="Admin" class="d-none d-sm-inline-block btn btn btn-primary shadow-sm">
        <i class="fas fa-long-arrow-alt-left text-white-50"></i><b> Quay trở lại</b>
    </a>
</div>

<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Thêm thể loại</h6>
    </div>
    <div class="card-body">
        <form class="formGenre" id="formGenre">
            <div class="row">
                <div class="form-group col-lg-3 col-sm-6">
                    <div class="upload_img">
                        <img src="~/admin/img/noimg.webp" class="img_name" id="imgPreview" />
                        <input type="file" name="img_name" accept="image/*" class="form-control" placeholder="Tải lên hình ảnh" id="photo">
                    </div>
                </div>
                <div class="col-lg-9 col-sm-6">
                    <div class="form-group">
                        <label for="name">Tên thể loại</label>
                        <input type="text" name="name" class="form-control" placeholder="Tên thể loại">
                    </div>
                    <div class="form-group">
                        <label for="description">Mô tả</label>
                        <textarea id="edit-text" placeholder="Mô tả" class="form-control" name="description"></textarea>
                    </div>
                    <button type="submit" class="btn btn-primary float-right">Lưu</button>
                </div>
            </div>
        </form>
    </div>
</div>
@section Scripts{
    <partial name="_ValidationScriptsPartial" />
}