L2M/Models/Artist.cs
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using System.Collections.Generic;

namespace L2M.Models
{
    [Table("artist")]
    public class Artist
    {
        [Key, Column("artist_id")]
        public int ArtistId { get; set; }

        [Required, StringLength(55)]
        public string Name { get; set; }

        public string? Description { get; set; }

        //[Required, StringLength(55)]
        //public string Type { get; set; }

        [Column("img_url")]
        public string? ImgUrl { get; set; }
        //Many to Many
        public ICollection<Album> Albums { get; set; }
        public ICollection<Song> Songs { get; set; }
        public ICollection<User> Users { get; set; }

        public ICollection<Artist_Album> Artist_Album { get; set; }
        public ICollection<Artist_Song> Artist_Song { get; set; }
        public ICollection<User_Artist> User_Artist { get; set; }
    }
}

L2M/Areas/Admin/Controllers/ArtistsController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using L2M.Data;
using L2M.Models;
using Microsoft.AspNetCore.Hosting;
using System.IO;
using L2M.Services;
using System.Diagnostics;

namespace L2M.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ArtistsController : Controller
    {
        private readonly IWebHostEnvironment _webHostEnviroment;

        public ArtistsController(IWebHostEnvironment hostEnvironment)
        {
            ArtistService.getContext();
            this._webHostEnviroment = hostEnvironment;
        }

        // GET: Artists
        public IActionResult Index()
        {
            return View(ArtistService.GetArtist());
        }

        // GET: Artists/Details/5
        public IActionResult Detail(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var artist = ArtistService.GetArtist((int)id);
            if (artist == null)
            {
                return NotFound();
            }

            return View(artist);
        }

        // GET: Artists/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Artists/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("Name,Description,ImgUrl")] Artist artist)
        {
            if (ModelState.IsValid)
            {
                var files = HttpContext.Request.Form.Files;
                if (files.Count == 0)
                {
                    artist.ImgUrl = "~/img/defaultImg.png";
                }else { 
                    string wwwRootPath = _webHostEnviroment.WebRootPath;
                    string path = wwwRootPath + "/img/artist/";
                    string fileName = Path.GetFileNameWithoutExtension(files[0].FileName);
                    string extension = Path.GetExtension(files[0].FileName);
                    fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
                    using (var fileStream = new FileStream(Path.Combine(path, fileName), FileMode.Create))
                    {
                        files[0].CopyTo(fileStream);
                    }
                    artist.ImgUrl = "~/img/artist/" + fileName;
                }
                int count  = ArtistService.PostArtist(artist);
                if (count > 0)
                {
                    TempData["Success"] = "Added";
                    return RedirectToAction(nameof(Index));
                } else
                {
                    TempData["Error"] = "Error add";
                    return View(artist);
                }
            } else
            {
                TempData["Error"] = "Validation";
                return View(artist);
            }
        }

        // GET: Artists/Edit/5
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var artist = ArtistService.GetArtist((int)id);
            if (artist == null)
            {
                return NotFound();
            }
            return View(artist);
        }

        // POST: Artists/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit([Bind("ArtistId,Name,Description,ImgUrl")] Artist artist)
        {
            if (ModelState.IsValid)
            {
                var oldObj = ArtistService.GetArtistToEdit(artist);
                string oldFileName = Path.GetFileNameWithoutExtension(oldObj.ImgUrl);
                string oldFileNameExtension = Path.GetExtension(oldObj.ImgUrl);
                var files = HttpContext.Request.Form.Files;
                if (files.Count > 0)
                {
                    string wwwRootPath = _webHostEnviroment.WebRootPath;
                    string path = wwwRootPath + "/img/artist/";
                    string fileName = Path.GetFileNameWithoutExtension(files[0].FileName);
                    string extension = Path.GetExtension(files[0].FileName);
                    if (oldFileName != "defaultImg" || oldFileName != "")
                    {
                        oldFileName = oldFileName + oldFileNameExtension;
                        var oldFile = Path.Combine(path, oldFileName);
                        if (System.IO.File.Exists(oldFile))
                        {
                            System.IO.File.Delete(oldFile);
                        }
                    }
                    fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
                    using (var fileStream = new FileStream(Path.Combine(path, fileName), FileMode.Create))
                    {
                        files[0].CopyTo(fileStream);
                    }
                    artist.ImgUrl = "~/img/artist/" + fileName;
                } else if (files.Count == 0)
                {
                    artist.ImgUrl = oldObj.ImgUrl;
                }
                int count = ArtistService.PutArtist(artist);
                if (count > 0)
                {
                    TempData["Success"] = "Edited";
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    TempData["Error"] = "Error edit";
                    return View(artist);
                }
                    
            }
            return View(artist);
        }

        public IActionResult Delete(int id)
        {
            var obj = ArtistService.GetArtist((int)id);
            if (obj == null)
            {
                TempData["Error"] = "Error";
                return RedirectToAction("Index");
            }
            string wwwRootPath = _webHostEnviroment.WebRootPath;
            string path = wwwRootPath + "/img/artist/";
            string oldFileName = Path.GetFileNameWithoutExtension(obj.ImgUrl);
            string oldFileNameExtension = Path.GetExtension(obj.ImgUrl);
            if (oldFileName != "defaultImg" || oldFileName != "")
            {
                oldFileName = oldFileName + oldFileNameExtension;
                var oldFile = Path.Combine(path, oldFileName);
                if (System.IO.File.Exists(oldFile))
                {
                    System.IO.File.Delete(oldFile);
                }
            }
            int count = ArtistService.DeleteArtist(id);
            if (count > 0)
            {
                TempData["Success"] = "Deleted";
                return RedirectToAction(nameof(Index));
            }
            TempData["Error"] = "Error delete";
            return RedirectToAction(nameof(Index));
        }
        // POST: Artists/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        //public IActionResult Delete(int id)
        //{
        //    var obj = ArtistService.GetArtist((int)id);
        //    if (obj == null)
        //    {
        //        TempData["Error"] = "Error";
        //        return RedirectToAction("Index");
        //    }
        //    string wwwRootPath = _webHostEnviroment.WebRootPath;
        //    string path = wwwRootPath + "/img/artist/";
        //    string oldFileName = Path.GetFileNameWithoutExtension(obj.ImgUrl);
        //    string oldFileNameExtension = Path.GetExtension(obj.ImgUrl);
        //    if (oldFileName != "defaultImg" || oldFileName != "")
        //    {
        //        oldFileName = oldFileName + oldFileNameExtension;
        //        var oldFile = Path.Combine(path, oldFileName);
        //        if (System.IO.File.Exists(oldFile))
        //        {
        //            System.IO.File.Delete(oldFile);
        //        }
        //    }
        //    ArtistService.DeleteArtist(id);
        //    TempData["Success"] = "Success";
        //    return RedirectToAction(nameof(Index));
        //}
    }
}

L2M/Areas/Admin/Views/Artists/Create.cshtml
@model L2M.Models.Artist
@{
    ViewBag.Title = "Thêm ca sĩ";
}

<!-- Page Heading -->
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Ca sĩ</h1>
    <a asp-controller="Artists" asp-action="Index" asp-area="Admin" class="d-none d-sm-inline-block btn btn btn-primary shadow-sm">
        <i class="fas fa-long-arrow-alt-left text-white-50"></i><b> Quay trở lại</b>
    </a>
</div>

<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Thêm ca sĩ</h6>
    </div>
    <div class="card-body">
        <form asp-action="Create" class="formArtist" id="formArtist" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="row">
                <div class="form-group col-lg-3 col-sm-6">
                    <div class="upload_img">
                        <img src="~/admin/img/noimg.webp" class="img_name" id="imgPreview" />
                        <input type="file" asp-for="ImgUrl" accept="image/*" class="form-control" placeholder="Tải lên hình ảnh" id="photo">
                    </div>
                </div>
                <div class="col-lg-9 col-sm-6">
                    <div class="form-group">
                        <label asp-for="Name">Tên ca sĩ</label>
                        <input type="text" asp-for="Name" class="form-control" placeholder="Tên ca sĩ">
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Description">Mô tả</label>
                        <textarea asp-for="Description" id="edit-text" placeholder="Mô tả" class="form-control"></textarea>
                    </div>
                    <button type="submit" class="btn btn-primary float-right">Lưu</button>
                </div>
            </div>
        </form>
    </div>
</div>
@section Scripts{
    <script>
        $(document).ready(function () {
            if ('@TempData["Success"]' == "Added") {
                swal("Đã thêm", "Thêm thành công!", "success");
            } else if ('@TempData["Error"]' == "Error add") {
                swal("Có lỗi", "Thêm không thành công! Vui lòng thử lại", "error");
            } if ('@TempData["Error"]' == "Validation") {
                swal("Cảnh báo", "Không được bỏ trống! Vui lòng nhập lại", "warning");
            }
        }
    </script>
    <partial name="_ValidationScriptsPartial" />
}

L2M/Areas/Admin/Views/Artists/Detail.cshtml
@model L2M.Models.Artist
@{
    ViewBag.Title = "Thông tin ca sĩ";
}

<!-- Page Heading -->
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Ca sĩ</h1>
    <a asp-controller="Artists" asp-action="Index" asp-area="Admin" class="d-none d-sm-inline-block btn btn btn-primary shadow-sm">
        <i class="fas fa-long-arrow-alt-left text-white-50"></i><b> Quay trở lại</b>
    </a>
</div>

<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Thông tin ca sĩ</h6>
    </div>
    <div class="card-body">
        <form asp-action="Edit" class="formArtist" id="formArtist" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ArtistId" />
            <div class="row">
                <div class="form-group col-lg-3 col-sm-6">
                    <div class="upload_img">
                        <img src="@Url.Content(@Model.ImgUrl)" class="img_name" id="imgPreview" />
                        <input type="file" asp-for="ImgUrl" accept="image/*" class="form-control" placeholder="Tải lên hình ảnh" id="photo">
                    </div>
                </div>
                <div class="col-lg-9 col-sm-6">
                    <div class="form-group">
                        <label asp-for="Name">Tên ca sĩ</label>
                        <input type="text" asp-for="Name" class="form-control" placeholder="Tên ca sĩ">
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="Description">Mô tả</label>
                        <textarea asp-for="Description" id="edit-text" placeholder="Mô tả" class="form-control"></textarea>
                    </div>
                    <button type="submit" class="btn btn-primary float-right">Lưu</button>
                </div>
            </div>
        </form>
    </div>
</div>
@section Scripts{
    <script>
        $(document).ready(function () {
            if ('@TempData["Error"]' == "Error edit") {
                swal("Có lỗi", "Đã có lỗi xảy ra, vui lòng thử lại!", "error");
            }
            else if ('@TempData["Success"]' == "Edited") {
                swal("Đã sửa", "Chỉnh sửa thành công!", "success");
            }
        });
    </script>
    <partial name="_ValidationScriptsPartial" />
}

L2M/Areas/Admin/Views/Artists/Details.cshtml
@{
    ViewBag.Title = "Thông tin ca sĩ";
}

<!-- Page Heading -->
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Ca sĩ</h1>
    <a asp-controller="Artists" asp-action="Index" asp-area="Admin" class="d-none d-sm-inline-block btn btn btn-primary shadow-sm">
        <i class="fas fa-long-arrow-alt-left text-white-50"></i><b> Quay trở lại</b>
    </a>
</div>

<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Thông tin ca sĩ</h6>
    </div>
    <div class="card-body">
        <form class="formArtist" id="formArtist">
            <div class="row">
                <div class="form-group col-lg-3 col-sm-6">
                    <div class="upload_img">
                        <img src="~/admin/img/noimg.webp" class="img_name" id="imgPreview" />
                        <input type="file" name="img_name" accept="image/*" class="form-control" placeholder="Tải lên hình ảnh" id="photo">
                    </div>
                </div>
                <div class="col-lg-9 col-sm-6">
                    <div class="form-group">
                        <label for="name">Tên ca sĩ</label>
                        <input type="text" name="name" class="form-control" placeholder="Tên ca sĩ">
                    </div>

                    <div class="form-group">
                        <label for="description">Mô tả</label>
                        <textarea id="edit-text" placeholder="Mô tả" class="form-control" name="description"></textarea>
                    </div>
                    <button type="submit" class="btn btn-primary float-right">Lưu</button>
                </div>
            </div>
        </form>
    </div>
</div>
@section Scripts{
<partial name="_ValidationScriptsPartial" />
}

L2M/Areas/Admin/Views/Artists/Edit.cshtml
@model L2M.Models.Artist
@{
    ViewBag.Title = "Chỉnh sửa ca sĩ";
}

<!-- Page Heading -->
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Ca sĩ</h1>
    <a asp-controller="Artists" asp-action="Index" asp-area="Admin" class="d-none d-sm-inline-block btn btn btn-primary shadow-sm">
        <i class="fas fa-long-arrow-alt-left text-white-50"></i><b> Quay trở lại</b>
    </a>
</div>

<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Chỉnh sửa ca sĩ</h6>
    </div>
    <div class="card-body">
        <form asp-action="Edit" class="formArtist" id="formArtist" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ArtistId" />
            <div class="row">
                <div class="form-group col-lg-3 col-sm-6">
                    <div class="upload_img">
                        <img src="@Url.Content(@Model.ImgUrl)" class="img_name" id="imgPreview" />
                        <input type="file" asp-for="ImgUrl" accept="image/*" class="form-control" placeholder="Tải lên hình ảnh" id="photo">
                    </div>
                </div>
                <div class="col-lg-9 col-sm-6">
                    <div class="form-group">
                        <label asp-for="Name">Tên ca sĩ</label>
                        <input type="text" asp-for="Name" class="form-control" placeholder="Tên ca sĩ">
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="Description">Mô tả</label>
                        <textarea asp-for="Description" id="edit-text" placeholder="Mô tả" class="form-control"></textarea>
                    </div>
                    <button type="submit" class="btn btn-primary float-right">Lưu</button>
                </div>
            </div>
        </form>
    </div>
</div>
@section Scripts{
    <script>
        $(document).ready(function () {
            if ('@TempData["Error"]' == "Error edit") {
                swal("Có lỗi", "Đã có lỗi xảy ra, vui lòng thử lại!", "error");
            } 
            else if ('@TempData["Success"]' == "Edited") {
                swal("Đã sửa", "Chỉnh sửa thành công!", "success");
            }
        });
    </script>
    <partial name="_ValidationScriptsPartial" />
}

L2M/Areas/Admin/Views/Artists/Index.cshtml
@model IEnumerable<L2M.Models.Artist>
@{
    ViewBag.Title = "Ca sĩ";
}

<!-- Page Heading -->
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Ca sĩ</h1>
    <a asp-controller="Artists" asp-action="Create" asp-area="Admin" class="d-none d-sm-inline-block btn btn btn-primary shadow-sm">
        <i class="fas fa-plus text-white-50"></i><b> Thêm ca sĩ</b>
    </a>
</div>

<!-- DataTales Example -->
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Danh sách ca sĩ</h6>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-hover" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>Hình đại diện</th>
                        <th>Tên</th>
                        <th>Thông tin</th>
                        <th>Tác vụ</th>
                    </tr>
                </thead>
                <tfoot>
                    <tr>
                        <th>Hình đại diện</th>
                        <th>Tên</th>
                        <th>Thông tin</th>
                        <th>Tác vụ</th>
                    </tr>
                </tfoot>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td><img src="@Url.Content(item.ImgUrl)" width="100" /></td>
                            <td>@item.Name</td>
                            <td>@item.Description</td>
                            <td>
                                <a class="text-primary mr-lg-2" asp-action="Edit" asp-route-id="@item.ArtistId"><i class="fas fa-edit"></i></a>&nbsp;
                                <a class="text-danger" onclick="Delete(event, 'ca sĩ', '@item.Name', '/Admin/Artists/Delete?id=@item.ArtistId')"><i class="fas fa-trash-alt"></i></a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>
@section Scripts{
    <script>
        //function Delete(event,type,name,url) {
        //    event.preventDefault();
        //    //console.log(event, id);
        //    swal({
        //        title: `Xóa ${type} "${name}"`,
        //        text: `Bạn chắc chắn muốn xóa ${type} "${name}"`,
        //        icon: "warning",
        //        buttons: {
        //            cancel: "Hủy",
        //            confirm: "Xóa"
        //        },
        //        dangerMode: true,
        //    }).then((isConfirm) => {
        //        if (isConfirm) {
        //            window.location.href = url;
        //        }
        //        else {
        //            swal("Đã hủy", "Dữ liệu của bạn an toàn", "error");
        //        }
        //    });
        //}
        $(document).ready(function () {
            if ('@TempData["Success"]' == "Deleted") {
                swal("Đã xóa", "Xóa thành công!", "success");
            }
            else if ('@TempData["Error"]' == "Error Delete") {
                swal("Có lỗi", "Đã có lỗi xảy ra, vui lòng thử lại!", "error");
            } else if ('@TempData["Success"]' == "Added") {
                swal("Đã thêm", "Thêm thành công!", "success");
            }
            else if ('@TempData["Success"]' == "Edited") {
                swal("Đã sửa", "Chỉnh sửa thành công!", "success");
            }
        })
    </script>
    <script type="text/javascript" src="~/admin/js/site.js"></script>
    <partial name="_ValidationScriptsPartial" />
}

L2M/Areas/Admin/Views/Artists/UpsertArtist.cshtml
@{
    ViewBag.Title = "Thêm ca sĩ";
}

<!-- Page Heading -->
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Ca sĩ</h1>
    <a asp-controller="Artists" asp-action="Index" asp-area="Admin" class="d-none d-sm-inline-block btn btn btn-primary shadow-sm">
        <i class="fas fa-long-arrow-alt-left text-white-50"></i><b> Quay trở lại</b>
    </a>
</div>

<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Thêm ca sĩ</h6>
    </div>
    <div class="card-body">
        <form class="formArtist" id="formArtist">
            <div class="row">
                <div class="form-group col-lg-3 col-sm-6">
                    <div class="upload_img">
                        <img src="~/admin/img/noimg.webp" class="img_name" id="imgPreview" />
                        <input type="file" name="img_name" accept="image/*" class="form-control" placeholder="Tải lên hình ảnh" id="photo">
                    </div>
                </div>
                <div class="col-lg-9 col-sm-6">
                    <div class="form-group">
                        <label for="name">Tên ca sĩ</label>
                        <input type="text" name="name" class="form-control" placeholder="Tên ca sĩ">
                    </div>

                    <div class="form-group">
                        <label for="description">Mô tả</label>
                        <textarea id="edit-text" placeholder="Mô tả" class="form-control" name="description"></textarea>
                    </div>
                    <button type="submit" class="btn btn-primary float-right">Lưu</button>
                </div>
            </div>
        </form>
    </div>
</div>
@section Scripts{
    <partial name="_ValidationScriptsPartial" />
}